### ISSUE TITLE
US-2.4: Admin CRUD operations

### ISSUE THREAD

**Issue by chrisegener22** [chrisegener22/LT-soen341projectF2023#6]
User Story Description

As a user, I want to be able to login as an administrator and be able to do CRUD operations on broker accounts, to manage the list of brokers.

User Acceptance Flow
- User goes to sign in page
- User clicks on "Admin"
- User logs in
- User clicks on "Manage Brokers"
- User performs CRUD operations on broker accounts

Acceptance Criteria
- [x] User acceptance flow is accepted
- [x] Documentation is present 
- [x] CRUD operations implemented
- [x] User is redirected to home page after logging in
- [x] "Manage Brokers" appears in nav menu after logging in

**Comment by NotTh3ta** [comment]
Not done, still need to make manage brokers page for admin
